# Generated by Django 5.1.15 on 2026-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Отправлено в Telegram')),
                ('whatsapp_notified', models.BooleanField(default=False, verbose_name='Уведомление WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
